site_name: HMIS Data Standards (Prototype)

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

plugins:
  - search
  - gen-files:
      scripts:
        - generate_docs.py
  - macros


nav:
  - Home: index.md
  - Data Dictionary:
      - Elements: 
          - 'All Elements': elements/index.md
          - !!accordion "Elements Tree":
              'Elements': 
                - type: glob
                  glob: "elements/*.md"
  - Value Lists:
      - 'All Value Lists': value-lists/index.md
      - !!accordion "Lists Tree":
          'Lists':
            - type: glob
              glob: "value-lists/*.md"

