site_name: HMIS Data Standards (Prototype)

theme:
  name: material

plugins:
  - search
  - gen-files:
      scripts:
        - generate_docs.py
  - macros


nav:
  - Home: index.md
  - Data Dictionary: dictionary.md
  - Data Manual: manual.md
  - Elements: elements/
