site_name: HMIS Data Standards (Prototype)

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

plugins:
  - search
  - gen-files:
      scripts:
        - generate_docs.py
  - macros

nav:
  - Home: index.md
  - Data Dictionary:
      - Elements:
          - Overview: elements-index.md
          - All Elements: "/elements/"
  - Value Lists:
      - Overview: value-lists-index.md
      - All Value Lists: "/value-lists/"
